### ISSUE TITLE
ESP32-C6 Support

### ISSUE THREAD

**Issue by Stengo** [espressif/esp-idf-cxx#23]
The library currently fails to compile for the ESP32-C6 target. Part of it seems to be the missing declaration of `INVALID_GPIOS`, but it looks like there's also something about the number of I2C that needs adjustment.

**Comment by 0xjakob** [comment]
@Stengo Thanks for letting us know! We'll take a look and fix this.

**Comment by baylf2000** [comment]
This library still fails compilation for the ESP32-C6 with errors `"No GPIOs defined for the current target"` and `"I2C_NUM_MAX must be equal to SOC_I2C_NUM"`.

**Comment by 0xjakob** [comment]
@Stengo @baylf2000 We've merged the corresponding PR #26, please let us know if you still encounter problems with any recently released targets.
